version: "3.6"

services:
  redis:
    image: redis:6.0.4-alpine
    restart: always
    environment:
      - REDIS_PASS=**None**
    ports:
      - 127.0.0.1:6379:6379

  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  mqtt:
    image: eclipse-mosquitto:1.6.10
    restart: always
    volumes:
      - mqttdata:/mosquitto/data
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:9001:9001

  mongo:
    image: mongo:4.4.2-bionic
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 127.0.0.1:27017:27017

  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

volumes:
  postgresdata:
  mqttdata:
  mongodata:
  mysqldata:
