version: "3.6"

services:
  redis:
    image: redis:6.0.4-alpine
    restart: always
    environment:
      - REDIS_PASS=**None**
    ports:
      - 127.0.0.1:6379:6379

  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  mqtt:
    image: eclipse-mosquitto:2.0.14
    restart: always
    volumes:
      - mqttdata:/mosquitto/data
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:9001:9001

  mongo:
    image: mongo:4.4.2-bionic
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 127.0.0.1:27017:27017

  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

  deepstream:
    image: deepstreamio/deepstream.io:6.0.0-alpine
    restart: always
    volumes:
      - ./config:/etc/deepstream
    depends_on:
      - redis
    ports:
      - 127.0.0.1:6020:6020
      - 127.0.0.1:6080:8080

  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - elasticdata:/usr/share/elasticsearch/data
  #   ports:
  #     - 127.0.0.1:9200:9200

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672

  nats:
    image: nats:2.9-alpine
    restart: always
    ports:
      - 127.0.0.1:4222:4222
      - 127.0.0.1:8222:8222

  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - opensearchdata:/usr/share/opensearch/data
    ports:
    - 127.0.0.1:9200:9200
    - 127.0.0.1:9600:9600

volumes:
  postgresdata:
  mqttdata:
  mongodata:
  mysqldata:
  elasticdata:
  rabbitmqdata:
  opensearchdata:
