version: "3.8"

services:
  redis:
    image: redis:6.0.4-alpine
    restart: always
    environment:
      - REDIS_PASS=**None**
    ports:
      - 127.0.0.1:6379:6379

  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  postgis:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgisdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:54345:5432

  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - timescaledata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:54350:5432

  mongo:
    image: mongo:4.4.2-bionic
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 127.0.0.1:27017:27017

  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

  emqx:
    image: emqx/emqx:5.5.0
    restart: always
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=${EMQX_HOST}
      - EMQX_DASHBOARD__DEFAULT_USERNAME=${EMQX_DASHBOARD_USERNAME}
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DASHBOARD_PASSWORD}
    volumes:
      - emqxdata:/opt/emqx/data
      - emqxetc:/opt/emqx/etc
      - emqxlog:/opt/emqx/log
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    extra_hosts:
      - host.docker.internal:host-gateway

  # deepstream:
  #   image: deepstreamio/deepstream.io:6.0.0-alpine
  #   restart: always
  #   volumes:
  #     - ./config:/etc/deepstream
  #   depends_on:
  #     - redis
  #   ports:
  #     - 127.0.0.1:6020:6020
  #     - 127.0.0.1:6080:8080

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672

  nats:
    image: nats:2.9-alpine
    restart: always
    ports:
      - 127.0.0.1:4222:4222
      - 127.0.0.1:8222:8222

  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearchdata:/usr/share/opensearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9600:9600

  # centrifugo:
  #   image: centrifugo/centrifugo:v5
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - ./config/config.json:/centrifugo/config.json
  #   command: centrifugo -c config.json

volumes:
  postgresdata:
  postgisdata:
  timescaledata:
  mongodata:
  mysqldata:
  rabbitmqdata:
  emqxdata:
  emqxetc:
  emqxlog:
  opensearchdata:
